name: electron
version: 0.0.2
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A Dart library for Electron desktop apps
homepage: https://github.com/rwl/electron
dependencies:
  barback: '>=0.15.2+4 <0.16.0'
